-- ====================================================================
-- مخطط وتغذية قاعدة بيانات Supabase (PostgreSQL) - نظام إدارة الصيدلية
-- Smart Pharmacy Management System (SPMS) - Supabase Cloud Database
-- ====================================================================

-- 1. جدول الشركات الموردة (Suppliers Table)
CREATE TABLE IF NOT EXISTS public.suppliers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    contact_person VARCHAR(150),
    phone VARCHAR(50),
    email VARCHAR(150),
    address TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. جدول الأدوية والمخزون الحرج (Medicines Table)
CREATE TABLE IF NOT EXISTS public.medicines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(250) NOT NULL,
    generic_name VARCHAR(250),
    category VARCHAR(120) NOT NULL,
    price NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
    stock_quantity INT NOT NULL DEFAULT 0,
    min_stock_alert INT NOT NULL DEFAULT 20,
    supplier_id BIGINT REFERENCES public.suppliers(id) ON DELETE SET NULL,
    expiry_date DATE,
    description TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. جدول فواتير الصرف والمبيعات (Orders Table)
CREATE TABLE IF NOT EXISTS public.orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_number VARCHAR(100),
    user_id INT DEFAULT 1,
    order_type VARCHAR(50) DEFAULT 'patient_sale',
    customer_name VARCHAR(150),
    payment_method VARCHAR(50) DEFAULT 'cash',
    total_amount NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
    status VARCHAR(50) DEFAULT 'completed',
    payment_status VARCHAR(50) DEFAULT 'paid',
    notes TEXT,
    order_date TIMESTAMPTZ DEFAULT NOW(),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. جدول تفاصيل بنود الفاتورة (Order Items Table)
CREATE TABLE IF NOT EXISTS public.order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT REFERENCES public.orders(id) ON DELETE CASCADE,
    medicine_id BIGINT REFERENCES public.medicines(id) ON DELETE SET NULL,
    medicine_name VARCHAR(250),
    quantity INT NOT NULL DEFAULT 1,
    unit_price NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
    total_price NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. جدول السجل التاريخي للصرف لتدريب نماذج الذكاء الاصطناعي (Sales History)
CREATE TABLE IF NOT EXISTS public.sales_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    medicine_id BIGINT REFERENCES public.medicines(id) ON DELETE CASCADE,
    quantity_sold INT NOT NULL DEFAULT 1,
    sale_date DATE NOT NULL DEFAULT CURRENT_DATE,
    day_of_week VARCHAR(20),
    month_num INT,
    season VARCHAR(30),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ====================================================================
-- إعداد سياسات الأمان (Row Level Security - RLS)
-- تفعيل الوصول الحر للقراءة والكتابة لبيئة العرض والتطبيق (Anon Access)
-- ====================================================================

ALTER TABLE public.suppliers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.medicines ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.order_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sales_history ENABLE ROW LEVEL SECURITY;

-- السماح بعمليات SELECT / INSERT / UPDATE / DELETE لجميع المستخدمين
DROP POLICY IF EXISTS "Public access suppliers" ON public.suppliers;
CREATE POLICY "Public access suppliers" ON public.suppliers FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Public access medicines" ON public.medicines;
CREATE POLICY "Public access medicines" ON public.medicines FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Public access orders" ON public.orders;
CREATE POLICY "Public access orders" ON public.orders FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Public access order_items" ON public.order_items;
CREATE POLICY "Public access order_items" ON public.order_items FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Public access sales_history" ON public.sales_history;
CREATE POLICY "Public access sales_history" ON public.sales_history FOR ALL USING (true) WITH CHECK (true);

-- ====================================================================
-- إدخال الشركات الموردة (Suppliers Initial Data)
-- ====================================================================

INSERT INTO public.suppliers (id, name, contact_person, phone, email, address) VALUES
(1, 'الشركة الوطنية للتموين الطبي / National Medical Supply', 'أ. خالد النجار', '01-445566', 'supply@national-med.com', 'صنعاء - شارع الزبيري'),
(2, 'مؤسسة الأدوية والمستلزمات الحديثة / Modern Pharma', 'د. سامي الحداد', '01-223344', 'info@modern-pharma.com', 'صنعاء - شارع حدة'),
(3, 'مستودع الأمل للأدوية والمضادات / Al-Amal Pharma', 'أ. طارق العريقي', '01-778899', 'sales@alamal-pharma.com', 'صنعاء - الحصبة')
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;

-- ====================================================================
-- إدخال قائمة الأدوية الشاملة (42+ دواء) في Supabase PostgreSQL
-- ====================================================================

INSERT INTO public.medicines (id, name, generic_name, category, price, stock_quantity, min_stock_alert, supplier_id, expiry_date, description) VALUES
(1, 'أوجمنتين 1 جم (Augmentin 1g)', 'أموكسيسيلين + كلافولانات (Amoxicillin + Clavulanate)', 'مضاد حيوي (Antibiotic)', 45.00, 85, 25, 1, '2026-11-30', 'مضاد حيوي واسع المجال لعلاج التهابات الجهاز التنفسي والمسالك.'),
(2, 'كلافوكس 1 جم (Clavox 1g)', 'أموكسيسيلين + كلافولانات (Amoxicillin + Clavulanate)', 'مضاد حيوي (Antibiotic)', 32.00, 40, 20, 2, '2026-10-15', 'مضاد حيوي واسع النطاق لعلاج العدوى البكتيرية الحادة.'),
(3, 'ميجاموكس 1 جم (Megamox 1g)', 'أموكسيسيلين + كلافولانات (Amoxicillin + Clavulanate)', 'مضاد حيوي (Antibiotic)', 28.00, 60, 20, 3, '2026-12-10', 'مضاد حيوي لعلاج التهابات الجيوب الأنفية والأذن الوسطى.'),
(4, 'كيورام 1 جم (Curam 1g)', 'أموكسيسيلين + كلافولانات (Amoxicillin + Clavulanate)', 'مضاد حيوي (Antibiotic)', 30.00, 55, 15, 1, '2027-03-20', 'علاج فعال للالتهابات البكتيرية الرئوية والجلدية.'),
(5, 'جلمنتين 2X 1 جم (Julmentin 2X 1g)', 'أموكسيسيلين + كلافولانات (Amoxicillin + Clavulanate)', 'مضاد حيوي (Antibiotic)', 26.50, 75, 20, 2, '2027-01-15', 'مضاد حيوي مكثف لالتهابات الأسنان والأنسجة الرخوة.'),
(6, 'أموكسيل 500 مجم (Amoxil 500mg)', 'أموكسيسيلين (Amoxicillin)', 'مضاد حيوي (Antibiotic)', 18.00, 120, 30, 1, '2027-02-28', 'مضاد حيوي كبسولات لعلاج العدوى البكتيرية العامة.'),
(7, 'هيموكس 500 مجم (H-Mox 500mg)', 'أموكسيسيلين (Amoxicillin)', 'مضاد حيوي (Antibiotic)', 12.00, 95, 25, 3, '2026-12-31', 'كبسولات أموكسيسيلين نقية سريعة المفعول.'),
(8, 'أموكسيدار 500 مجم (Amoxydar 500mg)', 'أموكسيسيلين (Amoxicillin)', 'مضاد حيوي (Antibiotic)', 14.50, 110, 20, 2, '2027-04-10', 'علاج بكتيريا الجهاز التنفسي والتهابات الحلق.'),
(9, 'زيثروماكس 500 مجم (Zithromax 500mg)', 'أزيثرومايسين (Azithromycin)', 'مضاد حيوي (Antibiotic)', 55.00, 35, 15, 1, '2026-11-20', 'مضاد حيوي ماكروليد كورس 3 أيام لعلاج الالتهاب الرئوي.'),
(10, 'أزوميسين 500 مجم (Azomycin 500mg)', 'أزيثرومايسين (Azithromycin)', 'مضاد حيوي (Antibiotic)', 28.00, 70, 20, 2, '2027-05-15', 'علاج عدوى الصدر والجيوب الأنفية واللوزتين.'),
(11, 'زيسروسين 500 مجم (Zisrocin 500mg)', 'أزيثرومايسين (Azithromycin)', 'مضاد حيوي (Antibiotic)', 22.00, 80, 20, 3, '2027-06-30', 'أزيثرومايسين عالي الجودة للالتهابات التناسلية والتنفسية.'),
(12, 'سيبروباي 500 مجم (Ciprobay 500mg)', 'سيبروفلوكساسين (Ciprofloxacin)', 'مضاد حيوي (Antibiotic)', 42.00, 45, 15, 1, '2026-10-30', 'فلوروكينولون لعلاج التهابات المسالك البولية المعقدة.'),
(13, 'سيبرودار 500 مجم (Ciprodar 500mg)', 'سيبروفلوكساسين (Ciprofloxacin)', 'مضاد حيوي (Antibiotic)', 19.00, 90, 25, 2, '2027-07-20', 'علاج النزلات المعوية البكتيرية والتهاب المسالك.'),
(14, 'تافانيك 500 مجم (Tavanic 500mg)', 'ليفوفلوكساسين (Levofloxacin)', 'مضاد حيوي (Antibiotic)', 68.00, 25, 10, 1, '2027-08-15', 'مضاد تنفسي قوي للالتهاب الرئوي الحاد.'),
(15, 'ليفودار 500 مجم (Levodar 500mg)', 'ليفوفلوكساسين (Levofloxacin)', 'مضاد حيوي (Antibiotic)', 34.00, 50, 15, 3, '2027-09-10', 'علاج عدوى البروستاتا والمسالك التنفسية السفلية.'),
(16, 'سيفودوكس 200 مجم (Cefodox 200mg)', 'سيفبودوكسيم (Cefpodoxime)', 'مضاد حيوي (Antibiotic)', 48.00, 38, 12, 2, '2026-12-15', 'سيفالوسبورين الجيل الثالث لعلاج التهاب القصبات.'),
(17, 'كلاسيد 500 مجم (Klacid 500mg)', 'كلاريثرومايسين (Clarithromycin)', 'مضاد حيوي (Antibiotic)', 62.00, 30, 10, 1, '2027-03-30', 'علاج جرثومة المعدة H. Pylori وعدوى الجلد.'),
(18, 'فلاجيل 500 مجم (Flagyl 500mg)', 'ميترونيدازول (Metronidazole)', 'مضاد حيوي ومطهر معوي (Antibiotic & Antiprotozoal)', 11.00, 160, 30, 2, '2027-10-25', 'مطهر ومضاد للطفيليات والبكتيريا اللاهوائية.'),
(19, 'بنادول إكسترا 500 مجم (Panadol Extra 500mg)', 'باراسيتامول + كافيين (Paracetamol + Caffeine)', 'مسكن وخافض حرارة (Analgesic & Antipyretic)', 12.00, 250, 50, 1, '2027-06-15', 'تسكين قوي وسريع للصداع النصفي والآلام الحادة.'),
(20, 'بنادول أدفانس 500 مجم (Panadol Advance 500mg)', 'باراسيتامول (Paracetamol)', 'مسكن وخافض حرارة (Analgesic & Antipyretic)', 9.50, 210, 40, 1, '2027-08-10', 'خافض حرارة لطيف على المعدة سريع الامتصاص.'),
(21, 'أدول 500 مجم (Adol 500mg)', 'باراسيتامول (Paracetamol)', 'مسكن وخافض حرارة (Analgesic & Antipyretic)', 7.50, 190, 35, 2, '2026-09-30', 'علاج آلام الجسم والحرارة وأعراض البرد.'),
(22, 'فيفادول 500 مجم (Fevadol 500mg)', 'باراسيتامول (Paracetamol)', 'مسكن وخافض حرارة (Analgesic & Antipyretic)', 6.00, 240, 45, 3, '2027-11-20', 'مسكن يومي آمن لمرضى الضغط وقرحة المعدة.'),
(23, 'باراسيتامول فارما 500 مجم (Paracetamol Pharma 500mg)', 'باراسيتامول (Paracetamol)', 'مسكن وخافض حرارة (Analgesic & Antipyretic)', 5.00, 180, 30, 3, '2027-08-20', 'أقراص باراسيتامول لتخفيف آلام العضلات والمفاصل.'),
(24, 'ريفانين 500 مجم (Revanin 500mg)', 'باراسيتامول (Paracetamol)', 'مسكن وخافض حرارة (Analgesic & Antipyretic)', 5.50, 150, 25, 2, '2027-04-15', 'تسكين الآلام البسيطة والمتوسطة.'),
(25, 'بروفين 400 مجم (Brufen 400mg)', 'إيبوبروفين (Ibuprofen)', 'مسكن ومضاد للالتهاب (NSAID / Anti-inflammatory)', 15.00, 130, 25, 1, '2027-01-10', 'مضاد التهاب ومسكن لآلام الأسنان والمفاصل والدورة.'),
(26, 'بروفين 600 مجم (Brufen 600mg)', 'إيبوبروفين (Ibuprofen)', 'مسكن ومضاد للالتهاب (NSAID / Anti-inflammatory)', 19.50, 85, 20, 1, '2027-02-15', 'جرعة قوية لعلاج التهاب المفاصل الروماتويدي والآلام الشديدة.'),
(27, 'سابوفين 400 مجم (Sapofen 400mg)', 'إيبوبروفين (Ibuprofen)', 'مسكن ومضاد للالتهاب (NSAID / Anti-inflammatory)', 11.00, 140, 30, 2, '2026-11-25', 'تسكين آلام العظام والعمود الفقري والصداع.'),
(28, 'إيبوفيل 400 مجم (Ibupophil 400mg)', 'إيبوبروفين (Ibuprofen)', 'مسكن ومضاد للالتهاب (NSAID / Anti-inflammatory)', 9.00, 105, 20, 3, '2027-05-30', 'مسكن سريع ومضاد للالتهابات والتورمات.'),
(29, 'فولتارين 50 مجم (Voltaren 50mg)', 'ديكلوفيناك الصوديوم (Diclofenac Sodium)', 'مسكن ومضاد للالتهاب (NSAID / Anti-inflammatory)', 22.00, 75, 20, 1, '2026-08-30', 'مسكن قوي لآلام الروماتيزم والانزلاق الغضروفي.'),
(30, 'ديكلوجين 50 مجم (Diclogen 50mg)', 'ديكلوفيناك الصوديوم (Diclofenac Sodium)', 'مسكن ومضاد للالتهاب (NSAID / Anti-inflammatory)', 11.00, 95, 20, 2, '2026-12-05', 'علاج نوبات النقرس والتهاب الأوتار.'),
(31, 'ديفيدو 75 مجم كبسول (Divido 75mg)', 'ديكلوفيناك الصوديوم (Diclofenac Sodium)', 'مسكن ومضاد للالتهاب (NSAID / Anti-inflammatory)', 28.00, 50, 15, 3, '2027-07-15', 'كبسولات ثنائية الإفراز لتسكين ممتد المفعول 24 ساعة.'),
(32, 'كتافلام 50 مجم (Cataflam 50mg)', 'ديكلوفيناك البوتاسيوم (Diclofenac Potassium)', 'مسكن ومضاد للالتهاب (NSAID / Anti-inflammatory)', 24.00, 80, 20, 1, '2027-03-25', 'ديكلوفيناك سريع الامتصاص لآلام ما بعد الجراحة والأسنان.'),
(33, 'رابيدوس 50 مجم (Rapidus 50mg)', 'ديكلوفيناك البوتاسيوم (Diclofenac Potassium)', 'مسكن ومضاد للالتهاب (NSAID / Anti-inflammatory)', 16.50, 90, 20, 2, '2027-01-30', 'تسكين فوري للصداع والتهابات الحلق والمفاصل.'),
(34, 'أولفين 50 مجم (Olfen 50mg)', 'ديكلوفيناك البوتاسيوم (Diclofenac Potassium)', 'مسكن ومضاد للالتهاب (NSAID / Anti-inflammatory)', 14.00, 65, 15, 3, '2026-10-20', 'مضاد لالتهابات الأوتار والالتواءات الرياضية.'),
(35, 'سيلبركس 200 مجم (Celebrex 200mg)', 'سيليكوكسيب (Celecoxib)', 'مسكن ومضاد للالتهاب (NSAID / Anti-inflammatory)', 65.00, 40, 10, 1, '2027-09-15', 'مثبط انتقائي لـ COX-2 آمن على المعدة لآلام المفاصل المزمنة.'),
(36, 'سيلكوكس 200 مجم (Celcox 200mg)', 'سيليكوكسيب (Celecoxib)', 'مسكن ومضاد للالتهاب (NSAID / Anti-inflammatory)', 32.00, 60, 15, 2, '2027-10-30', 'علاج خشونة الركبة والتهاب الفقار اللاصق.'),
(37, 'موبيك 15 مجم (Mobic 15mg)', 'ميلوكسيكام (Meloxicam)', 'مسكن ومضاد للالتهاب (NSAID / Anti-inflammatory)', 38.00, 45, 15, 1, '2027-06-20', 'قرص واحد يومياً لالتهاب المفاصل العظمي.'),
(38, 'بونستان فورت 500 مجم (Ponstan Forte 500mg)', 'حمض الميفيناميك (Mefenamic Acid)', 'مسكن ومضاد للالتهاب (NSAID / Anti-inflammatory)', 18.00, 85, 20, 2, '2027-04-30', 'مسكن لآلام الطمث وتقلصات الرحم وآلام الأسنان.'),
(39, 'سباسموبان 10 مجم (Spasmopan 10mg)', 'هيوسين بوتيل بروميد (Hyoscine Butylbromide)', 'مسكن لتقلصات الجهاز الهضمي (Antispasmodic)', 13.50, 110, 25, 3, '2027-08-15', 'علاج المغص الكلوي وتقلصات القولون العصبي.'),
(40, 'أوميبرازول 20 مجم (Omeprazole 20mg)', 'أوميبرازول (Omeprazole)', 'أدوية الجهاز الهضمي والمعدة (Gastrointestinal / PPI)', 20.00, 140, 30, 1, '2027-04-15', 'علاج قرحة المعدة وارتجاع المريء وحماية المعدة مع المسكنات.'),
(41, 'نيكسيوم 40 مجم (Nexium 40mg)', 'إيزوميبرازول (Esomeprazole)', 'أدوية الجهاز الهضمي والمعدة (Gastrointestinal / PPI)', 72.00, 55, 15, 2, '2027-11-30', 'مثبط قوي لمضخة البروتون لعلاج الحموضة الحادة.'),
(42, 'كونترولوك 40 مجم (Controloc 40mg)', 'بانتوبرازول (Pantoprazole)', 'أدوية الجهاز الهضمي والمعدة (Gastrointestinal / PPI)', 54.00, 65, 15, 3, '2027-07-25', 'حماية جدار المعدة من القرحة الناتجة عن الأدوية.')
ON CONFLICT (id) DO UPDATE SET 
    name = EXCLUDED.name,
    generic_name = EXCLUDED.generic_name,
    category = EXCLUDED.category,
    price = EXCLUDED.price,
    stock_quantity = EXCLUDED.stock_quantity,
    expiry_date = EXCLUDED.expiry_date,
    description = EXCLUDED.description;

-- ====================================================================
-- إدخال طلبات نموذجية وسجل المبيعات التاريخي في Supabase
-- ====================================================================

INSERT INTO public.orders (id, invoice_number, user_id, order_type, customer_name, payment_method, total_amount, status, payment_status, notes) VALUES
(101, 'INV-202608-001', 1, 'department_dispense', 'قسم الطوارئ والعناية المركزة', 'credit', 134.00, 'completed', 'paid', 'صرف فوري لحالات الطوارئ'),
(102, 'INV-202608-002', 1, 'patient_sale', 'محمد عبدالله الزبيري', 'cash', 76.00, 'completed', 'paid', 'صرف وصفة عيادة الباطنية'),
(103, 'INV-202608-003', 1, 'routine_restock', 'توريد مستودع الصيدلية الرئيسي', 'bank_transfer', 1250.00, 'completed', 'paid', 'أمر توريد ربع سنوي')
ON CONFLICT (id) DO UPDATE SET total_amount = EXCLUDED.total_amount;

INSERT INTO public.order_items (id, order_id, medicine_id, medicine_name, quantity, unit_price, total_price) VALUES
(1, 101, 1, 'أوجمنتين 1 جم (Augmentin 1g)', 2, 45.00, 90.00),
(2, 101, 29, 'فولتارين 50 مجم (Voltaren 50mg)', 2, 22.00, 44.00),
(3, 102, 19, 'بنادول إكسترا 500 مجم (Panadol Extra 500mg)', 3, 12.00, 36.00),
(4, 102, 40, 'أوميبرازول 20 مجم (Omeprazole 20mg)', 2, 20.00, 40.00),
(5, 103, 6, 'أموكسيل 500 مجم (Amoxil 500mg)', 50, 18.00, 900.00),
(6, 103, 35, 'سيلبركس 200 مجم (Celebrex 200mg)', 10, 35.00, 350.00)
ON CONFLICT (id) DO UPDATE SET quantity = EXCLUDED.quantity;

-- السجل التاريخي للصرف (Sales History for AI Training)
INSERT INTO public.sales_history (medicine_id, quantity_sold, sale_date, day_of_week, month_num, season) VALUES
(1, 3, '2026-07-01', 'Wednesday', 7, 'Summer'), (1, 2, '2026-07-02', 'Thursday', 7, 'Summer'),
(1, 4, '2026-07-03', 'Friday', 7, 'Summer'), (1, 2, '2026-07-04', 'Saturday', 7, 'Summer'),
(1, 3, '2026-07-05', 'Sunday', 7, 'Summer'), (1, 1, '2026-07-06', 'Monday', 7, 'Summer'),
(1, 3, '2026-07-07', 'Tuesday', 7, 'Summer'), (1, 2, '2026-07-08', 'Wednesday', 7, 'Summer'),
(19, 6, '2026-07-01', 'Wednesday', 7, 'Summer'), (19, 7, '2026-07-02', 'Thursday', 7, 'Summer'),
(19, 8, '2026-07-03', 'Friday', 7, 'Summer'), (19, 5, '2026-07-04', 'Saturday', 7, 'Summer'),
(29, 2, '2026-07-01', 'Wednesday', 7, 'Summer'), (29, 3, '2026-07-02', 'Thursday', 7, 'Summer'),
(40, 3, '2026-07-01', 'Wednesday', 7, 'Summer'), (40, 4, '2026-07-02', 'Thursday', 7, 'Summer');